### ISSUE TITLE
Respect protocol-relative URLs

### ISSUE THREAD

**Issue by laukstein** [fhemberger/manifest-validator#63]
> Line 234: Fallback resources must be from the same origin (i.e. identical protocol, hostname and port) as manifest file.
> //domain.com/*.jpg //domain.com/fallback.gif

**Comment by fhemberger** [comment]
If you submit a manifest file via upload or direct input, I can't validate if the manifest's origin is `domain.com` as well, thus, a warning is issued.

**Comment by laukstein** [comment]
For testcase use `https://laukstein.com/manifest.appcache`

**Comment by fhemberger** [comment]
The manifest is served from `https://laukstein.com/` and the FALLBACK resources from `//cdn.laukstein.com`, which are two different origins.

https://en.wikipedia.org/wiki/Same_origin_policy#Origin_determination_rules

**Comment by laukstein** [comment]
I would consider it as a spec issue. Anyway since it is deprecated and removed from spec, you can ignore any its related issues.
